### ISSUE TITLE
argparse vs. optparse

### ISSUE THREAD

**Issue by LazyDBA247-Perion** [saj/pynagioscheck#4]
Hi,
first of all thank you for the simple & great code/implementation for nagios checks, 
i am using it a lot :)
but i ask if you could replace optparse with argparse:

optparse can handle only optional arguments
argparse module supports action that consume a variable number of command-line args

you can read more  https://argparse.googlecode.com/svn/trunk/doc/argparse-vs-optparse.html

the transfer is quite simple...
https://argparse.googlecode.com/svn/trunk/doc/argparse-vs-optparse.html#upgrading-optparse-code

10x! in advnace

**Comment by saj** [comment]
Hello!

I am happy to hear you found some use for this little library.  Unfortunately, it is no longer maintained.  (I should really make a note of that somewhere, or remove this repo entirely.)  In the five+ years since I first wrote this library, I have grown to dislike the unjustified constraints it places on its users and would no longer recommend its use.

Funnily enough, argument parsing is part of the problem.  This library should not be responsible for parsing your command-line arguments.  It results in quirks like this one.  Users should be free to parse their arguments any way they please.  I would suppose my original (misguided) motivation for wrapping argument parsing functionality was to make it easy to solve simple problems.  As an unintended consequence of that design decision, this library made downright impossible to solve complex problems.  If your plugin configuration cannot be represented with the library's narrow-minded `add_option()` method then you are SOL.  This is poor design that I cannot easily change without breaking backwards compatibility.

You are, of course, free to fork this repository and modify it to suit your needs, though you would be better served by alternatives.  The [nagiosplugin](http://pythonhosted.org/nagiosplugin/tutorial/) library for Python appears to be of much better design, though I have no personal experience with it.  It is also available on the [PyPI](https://pypi.python.org/pypi/nagiosplugin/).  Source code is available [here](https://bitbucket.org/flyingcircus/nagiosplugin/overview) but please check the [ZPL license terms](http://old.zope.org/Resources/License/ZPL-2.1) since they are slightly more restrictive than the BSD 2-clause terms that apply to this software.

These days I write Nagios plugins in Go and would recommend [olorin/nagiosplugin](https://github.com/olorin/nagiosplugin) for plugin development in that language.
